#Bài tập 1: Thao tác với ma trận  
**Lý thuyết**:  
NumPy cung cấp các công cụ mạnh mẽ để thao tác ma trận, bao gồm tính toán các định thức, tìm nghịch đảo và tính toán các giá trị riêng và vectơ riêng.
  
**Đề bài**:  
Tạo ma trận 5x5 ngẫu nhiên và thực hiện các thao tác sau:  
* Tính định thức (determinant) của ma trận.  
* Tìm nghịch đảo (transpose) của ma trận.  
* Tính các giá trị riêng (eigent value) và vectơ riêng (eigent vector) của ma trận.   
(Phần này sẽ liên quan tới đại số tuyến tính, mọi người có thể tự tìm hiểu để hiểu chi tiết về các khái niệm trên)

<details>
  <summary>Hint</summary>

```python
import numpy as np

# Generate a random 5x5 matrix
matrix = np.random.rand(5, 5)

# Compute determinant
det = np.linalg.det(matrix)

# Find inverse
inverse = np.linalg.inv(matrix)

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)

```
</details>

In [5]:
# Your code here
import numpy as np
import random

random.seed(0)

mat = np.random.rand(5, 5)

#Determinant:
det = np.linalg.det(mat)

#Transpose:
inverse_mat = np.linalg.inv(mat)

#Eigen
eigen_values, eigen_vectors = np.linalg.eig(mat)

print("Det:", det, "\n")
print("Inverse Matrix: \n", inverse_mat, "\n")
print("Eigen Values:\n", eigen_values, "\n")
print("Eigen Vectors:\n", eigen_vectors, "\n")

Det: 0.0012093256400001824 

Inverse Matrix: 
 [[ -1.61848496   3.95708597   2.47244396 -22.80624746   7.25040938]
 [ 14.9002096  -10.71224821 -22.59498596 104.99325639 -26.27616198]
 [ -7.22515151   6.12129819   9.34137568 -42.69673014  10.81419717]
 [  5.45533965  -1.9898807   -6.17884464  24.19605405  -6.17932208]
 [ -7.5311188    0.9934159   11.9307704  -40.50883641   9.45685096]] 

Eigen Values:
 [ 2.32483319+0.j          0.29115848+0.j         -0.19946779+0.14145647j
 -0.19946779-0.14145647j  0.02987722+0.j        ] 

Eigen Vectors:
 [[ 0.32459467+0.j         -0.32939838+0.j         -0.32779081+0.37346354j
  -0.32779081-0.37346354j  0.14418726+0.j        ]
 [ 0.31540093+0.j          0.75478233+0.j          0.51266611+0.j
   0.51266611-0.j         -0.82803231+0.j        ]
 [ 0.68153349+0.j          0.18075225+0.j         -0.39488853+0.26761406j
  -0.39488853-0.26761406j  0.29094258+0.j        ]
 [ 0.26216237+0.j          0.05344184+0.j          0.05243083-0.11828628j
   0.05243083

# Bài tập 2: Optimization
**Lý thuyết:**  
Gradient descent là một thuật toán tối ưu hóa được sử dụng để cực tiểu hóa hàm bằng cách di chuyển lặp đi lặp lại theo hướng dốc xuống.

**Đề bài:**  
Triển khai gradient descent sử dụng NumPy để tối ưu hàm số sau:
 $$ f(x) = x^2 + 5 \sin(x) $$
<details>
  <summary>Hint</summary>

```python
import numpy as np

def gradient_descent(x, learning_rate, iterations):
    for _ in range(iterations):
        gradient = 2*x + 5*np.cos(x)  # Đạo hàm riêng theo x
        x = x - learning_rate * gradient # Cập nhật tham số
    return x

# Khởi tạo các hyperparameters
x_initial = 5  # Input đầu vào
learning_rate = 0.1 # Tốc độ học
iterations = 100 # Số lần lặp

# Run gradient descent
minima = gradient_descent(x_initial, learning_rate, iterations)
```

</details>

In [8]:
# Your code here
import numpy as np

#Hàm số f(x):
def f(x):
  return x**2 + 5*np.sin(x)

#Đạo hàm của f(x):
def df(x):
  return 2*x + 5*np.cos(x)

#Thuật toán GD:
def gradient_descent(x, learning_rate, iterations):
  for _ in range(iterations):
    gradient = df(x)
    x = x - learning_rate * gradient
  return x

#Khởi tạo giá trị ban đầu:
x0 = 5
#Tốc độ học:
learning_rate = 0.01
#Số lần lặp:
iterations= 1000

#Giá trị tối ưu:
x = gradient_descent(x0, learning_rate, iterations)
print('Optimal value of x:', x)
print('Optimal value of f(x):', f(x))

Optimal value of x: -1.1105105035811105
Optimal value of f(x): -3.2463942726915396


# Bài tập 3: Phân tích thống kê  
**Lý thuyết**:  
NumPy cung cấp các chức năng để phân tích thống kê, bao gồm tính toán giá trị trung bình (mean), trung vị (median), độ lệch chuẩn (standard deviation) và mối tương quan (correlation).  

**Đề Bài**:  
Thực hiện phân tích thống kê trên tập dữ liệu bai3.csv bằng NumPy:  
* Tính giá trị trung bình, trung vị và độ lệch chuẩn của tập dữ liệu.
* Tính toán ma trận tương quan giữa các biến khác nhau.
* Xác định các ngoại lệ trong tập dữ liệu bằng cách sử dụng điểm z.

<details>
  <summary>Hint</summary>

```python
  # Load dataset
  data = np.loadtxt('dataset.csv', delimiter=',')

  # Calculate mean, median, and standard deviation
  mean = np.mean(data, axis=0)
  median = np.median(data, axis=0)
  std_dev = np.std(data, axis=0)

  # Compute correlation matrix
  correlation_matrix = np.corrcoef(data, rowvar=False)

  # Identify outliers using z-scores
  z_scores = np.abs((data - mean) / std_dev)
  outliers = np.where(z_scores > 3)
```
</details>

In [14]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [15]:
file_path = "/content/drive/MyDrive/AI/AIO_2024/CODING PRACTICE/[MMC]-DATA-SCIENCE_NGUYỄN-HẢI-ĐĂNG/Labs/05 - Numpy trong Khoa học dữ liệu  & Final Project 1/Lab về nhà/bai3.csv"

In [16]:
with open(file_path, "r") as f:
  read = f.read()
  print(read)

Variable1,Variable2,Variable3,Variable4,Variable5
1.2,3.5,4.8,2.1,5.6
2.5,4.3,6.7,3.2,7.1
3.1,2.9,5.4,1.8,6.3
4.7,3.8,7.2,2.6,8.4
5.6,4.6,8.3,3.9,9.2


In [20]:
with open("dataset.csv", "w+") as wf:
  wf.write("Variable1,Variable2,Variable3,Variable4,Variable5\n")
  wf.write("1.2,3.5,4.8,2.1,5.6\n")
  wf.write("2.5,4.3,6.7,3.2,7.1\n")
  wf.write("3.1,2.9,5.4,1.8,6.3\n")
  wf.write("4.7,3.8,7.2,2.6,8.4\n")
  wf.write("5.6,4.6,8.3,3.9,9.2\n")
  wf.seek(0, 0)
  print(wf.read())

Variable1,Variable2,Variable3,Variable4,Variable5
1.2,3.5,4.8,2.1,5.6
2.5,4.3,6.7,3.2,7.1
3.1,2.9,5.4,1.8,6.3
4.7,3.8,7.2,2.6,8.4
5.6,4.6,8.3,3.9,9.2



In [23]:
# Your code here
import numpy as np
data = np.loadtxt("dataset.csv", delimiter=',', skiprows=1)
data

array([[1.2, 3.5, 4.8, 2.1, 5.6],
       [2.5, 4.3, 6.7, 3.2, 7.1],
       [3.1, 2.9, 5.4, 1.8, 6.3],
       [4.7, 3.8, 7.2, 2.6, 8.4],
       [5.6, 4.6, 8.3, 3.9, 9.2]])

In [25]:
 #Giá trị trung bình
 mean = np.mean(data, axis=0)
 mean

array([3.42, 3.82, 6.48, 2.72, 7.32])

In [30]:
np.mean(data[:, 0])

3.4200000000000004

In [26]:
#Giá trị trung vị
median = np.median(data, axis=0)
median

array([3.1, 3.8, 6.7, 2.6, 7.1])

In [31]:
np.median(data[:, 0])

3.1

In [32]:
#Độ lệch chuẩn
std_dev = np.std(data, axis=0)
std_dev

array([1.56639714, 0.59799666, 1.25443214, 0.75736385, 1.32272446])

In [33]:
#Ma trận tương quan giữa các biến
correlation_mat = np.corrcoef(data, rowvar=False)
correlation_mat

array([[1.        , 0.47784764, 0.89183434, 0.61500461, 0.94868903],
       [0.47784764, 1.        , 0.81104187, 0.97063145, 0.71505798],
       [0.89183434, 0.81104187, 1.        , 0.88457426, 0.98139657],
       [0.61500461, 0.97063145, 0.88457426, 1.        , 0.79617986],
       [0.94868903, 0.71505798, 0.98139657, 0.79617986, 1.        ]])

In [37]:
#Xác định các ngoại lệ
z_scores = np.abs((data - mean) / std_dev)
outliers = np.where(z_scores > 3)
print(z_scores, "\n")
outliers

[[1.4172651  0.53512005 1.3392514  0.81862899 1.30034641]
 [0.58733509 0.80268007 0.17537816 0.63377728 0.16632338]
 [0.20429046 1.53847014 0.86094733 1.21473979 0.77113566]
 [0.81716186 0.033445   0.57396488 0.15844432 0.81649658]
 [1.39172879 1.30435512 1.45085568 1.55803581 1.42130886]] 



(array([], dtype=int64), array([], dtype=int64))

# Bài 4: Thao tác với tensor
Đề cho một tensor đại diện cho một hình ảnh thang độ xám. Thực hiện các thao tác sau:

1. Reshape: Reshape tensor thành một hình dạng khác trong khi vẫn đảm bảo tổng số phần tử không đổi.
2. Transpose: Transpose tensor dọc theo các trục được chỉ định.
3. Slice: Trích xuất một tập hợp con của tensor bằng cách cắt dọc theo các kích thước được chỉ định.
4. Concatenate: Concatenate nhiều tensor dọc theo các trục được chỉ định.
5. Các phép toán theo phần tử: Thực hiện các phép toán theo phần tử như cộng, trừ, nhân và chia với các giá trị vô hướng hoặc các tensor khác.
6. Hoạt động rút gọn: Thực hiện các hoạt động rút gọn như tính tổng, trung bình, tối thiểu và tối đa dọc theo các trục được chỉ định.
7. Indexing: Truy cập các phần tử riêng lẻ hoặc các tensor phụ bằng cách sử dụng các chỉ số nguyên hoặc boolean mark.

<details>
  <summary>Hint</summary>

  ```python
    # 1. Reshape the tensor
    reshaped_tensor = image_tensor.reshape(1, 9)

    # 2. Transpose the tensor
    transposed_tensor = image_tensor.T

    # 3. Slice the tensor
    sliced_tensor = image_tensor[:2, :2]

    # 4. Concatenate tensors
    concatenated_tensor = np.concatenate((image_tensor, image_tensor), axis=0)

    # 5. Element-wise operations
    added_tensor = image_tensor + 0.1
    multiplied_tensor = image_tensor * 2

    # 6. Reduction operations
    sum_tensor = np.sum(image_tensor)
    mean_tensor = np.mean(image_tensor, axis=0)
    max_tensor = np.max(image_tensor, axis=1)

    # 7. Indexing
    element = image_tensor[1, 2]
  ```
</details>

In [11]:
image_tensor = np.array([
    [0.1, 0.2, 0.3],
    [0.4, 0.5, 0.6],
    [0.7, 0.8, 0.9]
])

In [39]:
image_tensor.shape

(3, 3)

In [42]:
#Thay đổi hình dạng tensor:
reshaped_tensor = image_tensor.reshape(1, 9)
reshaped_tensor.shape

(1, 9)

In [43]:
#Chuyển vị
transposed_tensor = image_tensor.T
transposed_tensor

array([[0.1, 0.4, 0.7],
       [0.2, 0.5, 0.8],
       [0.3, 0.6, 0.9]])

In [45]:
#Cắt dọc
sliced_tensor = image_tensor[:2, :2]
sliced_tensor

array([[0.1, 0.2],
       [0.4, 0.5]])

In [46]:
#Nối dọc
concatenated_tensor = np.concatenate((image_tensor, image_tensor), axis=0)
concatenated_tensor

array([[0.1, 0.2, 0.3],
       [0.4, 0.5, 0.6],
       [0.7, 0.8, 0.9],
       [0.1, 0.2, 0.3],
       [0.4, 0.5, 0.6],
       [0.7, 0.8, 0.9]])

In [49]:
image_tensor + 0.1

array([[0.2, 0.3, 0.4],
       [0.5, 0.6, 0.7],
       [0.8, 0.9, 1. ]])

In [50]:
image_tensor * 2

array([[0.2, 0.4, 0.6],
       [0.8, 1. , 1.2],
       [1.4, 1.6, 1.8]])

In [51]:
#Rút gọn
np.sum(image_tensor)

4.5

In [52]:
np.mean(image_tensor, axis=0)

array([0.4, 0.5, 0.6])

In [53]:
np.max(image_tensor, axis=1)

array([0.3, 0.6, 0.9])

In [56]:
#Truy cập
image_tensor[0, 0]

0.1