In [1]:
import numpy as np
np.random.seed(42)

# Problem 1: Tạo hai ma trận 3x3 với các phần tử integer ngẫu nhiên từ 1 - 10.

In [3]:
# Your code here
mat1 = np.random.randint(1, 11, size=(3, 3))
mat2 = np.random.randint(1, 11, size=(3, 3))
print(mat1)
print(mat2)

[[ 6  2  5]
 [ 1 10  6]
 [ 9  1 10]]
[[3 7 4]
 [9 3 5]
 [3 7 5]]


# Problem 2: Thực hiện phép cộng phần tử, nhân từng phần tử, tích vô hướng với hai ma trận vừa được tạo.


In [4]:
# Your code here
sum_mat = mat1 + mat2
sum_mat

array([[ 9,  9,  9],
       [10, 13, 11],
       [12,  8, 15]])

In [11]:
sum_mat = np.add(mat1, mat2)
sum_mat

array([[ 9,  9,  9],
       [10, 13, 11],
       [12,  8, 15]])

In [5]:
product_mat = mat1 * mat2
product_mat

array([[18, 14, 20],
       [ 9, 30, 30],
       [27,  7, 50]])

In [12]:
product_mat = np.multiply(mat1, mat2)
product_mat

array([[18, 14, 20],
       [ 9, 30, 30],
       [27,  7, 50]])

In [7]:
dot_product = np.dot(mat1, mat2)
dot_product

array([[ 51,  83,  59],
       [111,  79,  84],
       [ 66, 136,  91]])

# Problem 3: VIết hàm nhận vào một mảng Numpy, sau đó trả về tổng tất cả các phần tử của chúng


In [9]:
# Your code here
import numpy as np

def sum_array(arr):
    return np.sum(arr)

print(sum_array(mat1))

50
